version: 2
updates:
- package-ecosystem: "npm"
  directory: "/frontend"
  target-branch: "main"
  schedule:
    interval: "weekly"
- package-ecosystem: "npm"
  directory: "/backend"
  target-branch: "main"
  schedule:
    interval: "weekly"
