title: "Statusreport für die KW [KW] ([Wochenstart] - [Wochenende])"

body:
  - type: dropdown
    attributes:
      label: "Aktueller Status:"
      options:
        - 🟩
        - 🟨
        - 🟧
        - 🟥
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Was wurde diese Woche erreicht?"
      description: "Beschreiben Sie hier, was in dieser Woche erreicht wurde"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Was sind die nächsten Schritte?"
      description: "Beschreiben Sie hier, was die nächsten Schritte sind"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Sind in dieser Woche Probleme aufgetreten?"
      description: "Beschreiben Sie hier, welche Probleme in dieser Woche aufgetreten sind"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Was wurde aus dieser Woche gelernt?"
      description: "Beschreiben Sie hier, was Sie aus dieser Woche gelernt haben"
    validations:
      required: true
